/**
 * GENERATED FILE — do not hand-edit.
 *
 * Produced by scripts/gen-types.sh from the backend's live OpenAPI
 * schema. Re-run that script after changing any backend Pydantic
 * model (backend/app/models/*.py) — do not edit this file directly,
 * your changes will be overwritten on the next run.
 */

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Decision */
        post: operations["create_decision_api_v1_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Decision
         * @enum {string}
         */
        Decision: "APPROVE" | "DECLINE";
        /** DecisionTrace */
        DecisionTrace: {
            /** Transaction Id */
            transaction_id: string;
            decision: components["schemas"]["Decision"];
            /** Nodes */
            nodes: components["schemas"]["NodeResult"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NodeResult */
        NodeResult: {
            /** Node Id */
            node_id: string;
            status: components["schemas"]["NodeStatus"];
            /** Reason */
            reason: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * NodeStatus
         * @enum {string}
         */
        NodeStatus: "PASSED" | "FAILED" | "SKIPPED";
        /** TransactionInput */
        TransactionInput: {
            /** Transaction Id */
            transaction_id: string;
            /** Account Id */
            account_id: string;
            /** Amount */
            amount: number | string;
            /** Currency */
            currency: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Ip Address */
            ip_address: string;
            /** Ip Country */
            ip_country: string;
            /** Is Known Proxy */
            is_known_proxy: boolean;
            /** Is Known Datacenter */
            is_known_datacenter: boolean;
            /** Billing Country */
            billing_country: string;
            /** Shipping Country */
            shipping_country: string;
            /** Account Home Country */
            account_home_country: string;
            /** Device Id */
            device_id: string;
            /** Device Recognized */
            device_recognized: boolean;
            /** Distinct Accounts On Device 24H */
            distinct_accounts_on_device_24h: number;
            /** Transactions From Account 1H */
            transactions_from_account_1h: number;
            /** Transactions From Account 24H */
            transactions_from_account_24h: number;
            /** Account Age Days */
            account_age_days: number;
            /** Email Verified */
            email_verified: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_decision_api_v1_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionTrace"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}

// Flat aliases so the rest of the frontend can import
// TransactionInput / DecisionTrace / etc. directly instead of
// reaching into components["schemas"][...] everywhere.
export type TransactionInput = components["schemas"]["TransactionInput"];
export type DecisionTrace = components["schemas"]["DecisionTrace"];
export type NodeResult = components["schemas"]["NodeResult"];
export type NodeStatus = components["schemas"]["NodeStatus"];
export type Decision = components["schemas"]["Decision"];
