#!/usr/bin/env bash
#
# Regenerates frontend/src/types/trace.gen.ts from the backend's live
# OpenAPI schema (backend/app/main.py -> app.openapi()). No server needs
# to be running — the schema is exported directly from the FastAPI app
# object.
#
# trace.gen.ts is a GENERATED file from this point on. Never hand-edit
# it — re-run this script after changing any backend Pydantic model
# instead.

set -euo pipefail

# Resolve to a Windows-native path (pwd -W, a Git-Bash/MSYS extension)
# rather than plain `pwd`'s MSYS-style /c/... path — the schema/types
# files below get opened by native Windows python.exe/node.exe, which
# don't understand /c/... or /tmp.
if pwd -W >/dev/null 2>&1; then
  ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -W)"
else
  ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
BACKEND_DIR="$ROOT_DIR/backend"
FRONTEND_DIR="$ROOT_DIR/frontend"
OUT_FILE="$FRONTEND_DIR/src/types/trace.gen.ts"

if [ -x "$ROOT_DIR/.venv/Scripts/python.exe" ]; then
  PYTHON="$ROOT_DIR/.venv/Scripts/python.exe"
elif [ -x "$ROOT_DIR/.venv/bin/python" ]; then
  PYTHON="$ROOT_DIR/.venv/bin/python"
else
  PYTHON="python3"
fi

# Placed under the repo root (not /tmp) so the path is valid for both
# bash and any native Windows tool that opens it.
SCHEMA_FILE="$(mktemp "$ROOT_DIR/.gen-types-schema.XXXXXX")"
RAW_TYPES_FILE="$(mktemp "$ROOT_DIR/.gen-types-raw.XXXXXX")"
trap 'rm -f "$SCHEMA_FILE" "$RAW_TYPES_FILE"' EXIT

# @redocly/openapi-core (used by openapi-typescript to resolve the
# schema) mishandles spaces in a local file path it treats as a base
# URI. Convert to the 8.3 short-path form to sidestep that — harmless
# no-op on any path/OS where it isn't needed or isn't available.
if command -v powershell.exe >/dev/null 2>&1; then
  to_short_path() {
    powershell.exe -NoProfile -Command \
      "(New-Object -ComObject Scripting.FileSystemObject).GetFile('$1').ShortPath" \
      | tr -d '\r'
  }
  SCHEMA_FILE="$(to_short_path "$SCHEMA_FILE")"
  RAW_TYPES_FILE="$(to_short_path "$RAW_TYPES_FILE")"
fi

echo "Exporting OpenAPI schema from the backend app..."
(
  cd "$BACKEND_DIR"
  "$PYTHON" -c "
import json
from app.main import app

with open(r'$SCHEMA_FILE', 'w') as f:
    json.dump(app.openapi(), f)
"
)

echo "Generating TypeScript types with openapi-typescript..."
# Run fully isolated via `npx --package` rather than as a project
# devDependency: openapi-typescript needs the classic TS Compiler API
# (ts.factory), which this project's pinned typescript@7 doesn't
# provide the same way. Pinning an isolated typescript@5 here keeps
# the generator working without downgrading the project's real
# TypeScript version.
(
  cd "$FRONTEND_DIR"
  npx --yes --package=openapi-typescript@7.13.0 --package=typescript@5.9.3 -- \
    openapi-typescript "$SCHEMA_FILE" -o "$RAW_TYPES_FILE"
)

{
  echo "/**"
  echo " * GENERATED FILE — do not hand-edit."
  echo " *"
  echo " * Produced by scripts/gen-types.sh from the backend's live OpenAPI"
  echo " * schema. Re-run that script after changing any backend Pydantic"
  echo " * model (backend/app/models/*.py) — do not edit this file directly,"
  echo " * your changes will be overwritten on the next run."
  echo " */"
  echo
  cat "$RAW_TYPES_FILE"
  echo
  echo "// Flat aliases so the rest of the frontend can import"
  echo "// TransactionInput / DecisionTrace / etc. directly instead of"
  echo "// reaching into components[\"schemas\"][...] everywhere."
  echo 'export type TransactionInput = components["schemas"]["TransactionInput"];'
  echo 'export type DecisionTrace = components["schemas"]["DecisionTrace"];'
  echo 'export type NodeResult = components["schemas"]["NodeResult"];'
  echo 'export type NodeStatus = components["schemas"]["NodeStatus"];'
  echo 'export type Decision = components["schemas"]["Decision"];'
} > "$OUT_FILE"

echo "Wrote $OUT_FILE"
